### ISSUE TITLE
ECR option doesn't work

### ISSUE THREAD

**Issue by leandrofinger** [opspresso/action-docker#11]
I've been trying to use the ECR but it always runs as docker, even setting args as "--ecr" or setting CMD env as "--ecr".

**UPDATE:**
After investigating, I figured out that the correct input argument is `registry-type` instead of `args`. That way, I've created a PR to fix the examples at README file: https://github.com/opspresso/action-docker/pull/12

**Comment by nalbam** [comment]
Thanks for your comments.
But I solved it another way.
I deleted the inputs.
So, it works as written in the README.

```
      - name: Docker Build & Push to AWS ECR
        uses: opspresso/action-docker@master
        with:
          args: --ecr
```

https://github.com/opspresso/action-docker/commit/787bb6ebb4746dd69aad240bc5bb513179016d01

https://github.com/opspresso/action-docker/commit/82211e44bdea17144cdd1312dc975f1ed5f48eb2
