### ISSUE TITLE
Dockerfile not found

### ISSUE THREAD

**Issue by LovroG05** [opspresso/action-docker#16]
```
$ docker buildx build  -t ClassCompanion/discord-bot:latest -f Dockerfile .
#1 [internal] booting buildkit
#1 pulling image moby/buildkit:buildx-stable-1
#1 pulling image moby/buildkit:buildx-stable-1 0.2s done
#1 creating container buildx_buildkit_ops-16447041850
#1 creating container buildx_buildkit_ops-16447041850 5.1s done
#1 DONE 5.3s

#2 [internal] load build definition from Dockerfile
#2 transferring dockerfile: 2B 0.0s done
#2 DONE 0.0s

#3 [internal] load .dockerignore
#3 transferring context:
#3 CANCELED
error: failed to solve: failed to read dockerfile: open /tmp/buildkit-mount061561675/Dockerfile: no such file or directory
```

i have got Dockerfile in the root of the project, is that the correct place? Also tried with Dockerfile in .github/workflows/

my usage:
```
- name: Build & Push to Docker Hub
        uses: opspresso/action-docker@master
        with:
          args: --docker
        env:
          USERNAME: ${{ secrets.DOCKER_USERNAME }}
          PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          TAG_NAME: ${{ steps.get_release.outputs.tag_name }}
          BUILDX: "true"
```
